import { PermissionRiskLevel } from '../../core/classification-types.js';
import NonePreset from './none.js';

export default class StrictPreset extends NonePreset {
  public constructor() {
    super({
      UseAnyApiClient: PermissionRiskLevel.BLOCKED,
      BypassMFAForUiLogins: PermissionRiskLevel.BLOCKED,
      ManageNamedCredentials: PermissionRiskLevel.CRITICAL,
      ImportCustomObjects: PermissionRiskLevel.CRITICAL,
      ManageSandboxes: PermissionRiskLevel.CRITICAL,
      ManageDevSandboxes: PermissionRiskLevel.CRITICAL,
      CustomizeApplication: PermissionRiskLevel.CRITICAL,
      ModifyMetadata: PermissionRiskLevel.CRITICAL,
      AuthorApex: PermissionRiskLevel.CRITICAL,
      DebugApex: PermissionRiskLevel.CRITICAL,
      ManageAuthProviders: PermissionRiskLevel.CRITICAL,
      Packaging2: PermissionRiskLevel.CRITICAL,
      Packaging2Delete: PermissionRiskLevel.CRITICAL,
      Packaging2PromoteVersion: PermissionRiskLevel.CRITICAL,
      InstallPackaging: PermissionRiskLevel.CRITICAL,
      ViewClientSecret: PermissionRiskLevel.CRITICAL,
      ExternalClientAppAdmin: PermissionRiskLevel.CRITICAL,
      CanInsertFeedSystemFields: PermissionRiskLevel.CRITICAL,
      ManageExternalConnections: PermissionRiskLevel.CRITICAL,
      CodeBuilderUser: PermissionRiskLevel.CRITICAL,
      ManageCertificates: PermissionRiskLevel.HIGH,
      ExportReport: PermissionRiskLevel.HIGH,
      ViewSetup: PermissionRiskLevel.HIGH,
      ApiEnabled: PermissionRiskLevel.HIGH,
      ViewAllData: PermissionRiskLevel.HIGH,
      ModifyAllData: PermissionRiskLevel.HIGH,
      ManageTwoFactor: PermissionRiskLevel.HIGH,
      ManageRemoteAccess: PermissionRiskLevel.HIGH,
      CanApproveUninstalledApps: PermissionRiskLevel.HIGH,
      AssignPermissionSets: PermissionRiskLevel.HIGH,
      ManageRoles: PermissionRiskLevel.HIGH,
      ManageIpAddresses: PermissionRiskLevel.HIGH,
      ManageSharing: PermissionRiskLevel.HIGH,
      ManageInternalUsers: PermissionRiskLevel.HIGH,
      ManagePasswordPolicies: PermissionRiskLevel.HIGH,
      ManageLoginAccessPolicies: PermissionRiskLevel.HIGH,
      ManageCustomPermissions: PermissionRiskLevel.HIGH,
      FreezeUsers: PermissionRiskLevel.HIGH,
      AccessContentBuilder: PermissionRiskLevel.HIGH,
      NewReportBuilder: PermissionRiskLevel.HIGH,
      ImportLeads: PermissionRiskLevel.HIGH,
      ViewEncryptedData: PermissionRiskLevel.HIGH,
      EditBrandTemplates: PermissionRiskLevel.HIGH,
      OverrideForecasts: PermissionRiskLevel.HIGH,
      ViewAllForecasts: PermissionRiskLevel.HIGH,
      ResetPasswords: PermissionRiskLevel.HIGH,
      ManageNetworks: PermissionRiskLevel.HIGH,
      ViewAllUsers: PermissionRiskLevel.HIGH,
      ModerateNetworkUsers: PermissionRiskLevel.HIGH,
      ViewHealthCheck: PermissionRiskLevel.HIGH,
      ManageHealthCheck: PermissionRiskLevel.HIGH,
      ManageSubscriptions: PermissionRiskLevel.HIGH,
      ViewRoles: PermissionRiskLevel.HIGH,
      ViewAllProfiles: PermissionRiskLevel.HIGH,
      MonitorLoginHistory: PermissionRiskLevel.HIGH,
      ManagePackageLicenses: PermissionRiskLevel.HIGH,
      ScheduleReports: PermissionRiskLevel.MEDIUM,
      EmailMass: PermissionRiskLevel.MEDIUM,
      DataExport: PermissionRiskLevel.MEDIUM,
      RunReports: PermissionRiskLevel.MEDIUM,
      ApproveContract: PermissionRiskLevel.MEDIUM,
      ActivateContract: PermissionRiskLevel.MEDIUM,
      ActivateOrder: PermissionRiskLevel.MEDIUM,
      DeleteActivatedContract: PermissionRiskLevel.MEDIUM,
      ManageQuotas: PermissionRiskLevel.MEDIUM,
      ManageUsers: PermissionRiskLevel.HIGH,
      LightningExperienceUser: PermissionRiskLevel.LOW,
      PasswordNeverExpires: PermissionRiskLevel.LOW,
      ActivitiesAccess: PermissionRiskLevel.LOW,
      ForceTwoFactor: PermissionRiskLevel.LOW,
    });
  }
}
